version: '3.11'

services:
    app:
        build: ./
        command: streamlit run app.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: streamlitapp:latest